# Generated by Django 4.2.6 on 2024-02-14 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('body', models.TextField(max_length=400, verbose_name='Body')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('loves', models.PositiveIntegerField(default=0, verbose_name='Loves')),
                ('cares', models.PositiveIntegerField(default=0, verbose_name='Cares')),
                ('angrys', models.PositiveIntegerField(default=0, verbose_name='Angrys')),
                ('wows', models.PositiveIntegerField(default=0, verbose_name='Wows')),
                ('sads', models.PositiveIntegerField(default=0, verbose_name='Sads')),
                ('laughs', models.PositiveIntegerField(default=0, verbose_name='Laughs')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('views_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='posts/images/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('loves', models.PositiveIntegerField(default=0)),
                ('cares', models.PositiveIntegerField(default=0)),
                ('angrys', models.PositiveIntegerField(default=0)),
                ('wows', models.PositiveIntegerField(default=0)),
                ('sads', models.PositiveIntegerField(default=0)),
                ('laughs', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
                ('media', models.ManyToManyField(related_name='posts', to='blog.media')),
            ],
            options={
                'verbose_name_plural': 'Post',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('purchase_link', models.URLField(blank=True)),
                ('is_downloadable', models.BooleanField(default=False, verbose_name='Is Downloadable?')),
                ('delivery_type', models.CharField(choices=[('downloadable', 'Downloadable'), ('physical', 'Physical Delivery via Mail')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('body', models.TextField(verbose_name='Body')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('loves', models.PositiveIntegerField(default=0, verbose_name='Loves')),
                ('cares', models.PositiveIntegerField(default=0, verbose_name='Cares')),
                ('angrys', models.PositiveIntegerField(default=0, verbose_name='Angrys')),
                ('wows', models.PositiveIntegerField(default=0, verbose_name='Wows')),
                ('sads', models.PositiveIntegerField(default=0, verbose_name='Sads')),
                ('laughs', models.PositiveIntegerField(default=0, verbose_name='Laughs')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.post')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies_to', to='blog.reply')),
            ],
            options={
                'verbose_name': 'Reply',
                'verbose_name_plural': 'Replies',
                'ordering': ['created_on'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies_to', to='blog.comment'),
        ),
    ]
